// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AssetService.proto
// </auto-generated>
// Original file comments:
// Asset Service
//
// Consumer service on the management of assets.
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace  {
  public static partial class AssetService
  {
    static readonly string __ServiceName = "AssetService";

    static readonly grpc::Marshaller<global::CreateAssetClassRequest> __Marshaller_CreateAssetClassRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CreateAssetClassRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CreateAssetClassResponse> __Marshaller_CreateAssetClassResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CreateAssetClassResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DeleteAssetClassRequest> __Marshaller_DeleteAssetClassRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DeleteAssetClassRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DeleteAssetClassResponse> __Marshaller_DeleteAssetClassResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DeleteAssetClassResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CreateAssetRequest> __Marshaller_CreateAssetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CreateAssetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CreateAssetResponse> __Marshaller_CreateAssetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CreateAssetResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DeleteAssetRequest> __Marshaller_DeleteAssetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DeleteAssetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::DeleteAssetResponse> __Marshaller_DeleteAssetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DeleteAssetResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TransferAssetRequest> __Marshaller_TransferAssetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TransferAssetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TransferAssetResponse> __Marshaller_TransferAssetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TransferAssetResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ExecuteTransactionRequest> __Marshaller_ExecuteTransactionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ExecuteTransactionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ExecuteTransactionResponse> __Marshaller_ExecuteTransactionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ExecuteTransactionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::CreateAssetClassRequest, global::CreateAssetClassResponse> __Method_CreateAssetClass = new grpc::Method<global::CreateAssetClassRequest, global::CreateAssetClassResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateAssetClass",
        __Marshaller_CreateAssetClassRequest,
        __Marshaller_CreateAssetClassResponse);

    static readonly grpc::Method<global::DeleteAssetClassRequest, global::DeleteAssetClassResponse> __Method_DeleteAssetClass = new grpc::Method<global::DeleteAssetClassRequest, global::DeleteAssetClassResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteAssetClass",
        __Marshaller_DeleteAssetClassRequest,
        __Marshaller_DeleteAssetClassResponse);

    static readonly grpc::Method<global::CreateAssetRequest, global::CreateAssetResponse> __Method_CreateAsset = new grpc::Method<global::CreateAssetRequest, global::CreateAssetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateAsset",
        __Marshaller_CreateAssetRequest,
        __Marshaller_CreateAssetResponse);

    static readonly grpc::Method<global::DeleteAssetRequest, global::DeleteAssetResponse> __Method_DeleteAsset = new grpc::Method<global::DeleteAssetRequest, global::DeleteAssetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteAsset",
        __Marshaller_DeleteAssetRequest,
        __Marshaller_DeleteAssetResponse);

    static readonly grpc::Method<global::TransferAssetRequest, global::TransferAssetResponse> __Method_TransferAsset = new grpc::Method<global::TransferAssetRequest, global::TransferAssetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TransferAsset",
        __Marshaller_TransferAssetRequest,
        __Marshaller_TransferAssetResponse);

    static readonly grpc::Method<global::ExecuteTransactionRequest, global::ExecuteTransactionResponse> __Method_ExecuteTransaction = new grpc::Method<global::ExecuteTransactionRequest, global::ExecuteTransactionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExecuteTransaction",
        __Marshaller_ExecuteTransactionRequest,
        __Marshaller_ExecuteTransactionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AssetServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AssetService</summary>
    public abstract partial class AssetServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::CreateAssetClassResponse> CreateAssetClass(global::CreateAssetClassRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DeleteAssetClassResponse> DeleteAssetClass(global::DeleteAssetClassRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::CreateAssetResponse> CreateAsset(global::CreateAssetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DeleteAssetResponse> DeleteAsset(global::DeleteAssetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::TransferAssetResponse> TransferAsset(global::TransferAssetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ExecuteTransactionResponse> ExecuteTransaction(global::ExecuteTransactionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AssetService</summary>
    public partial class AssetServiceClient : grpc::ClientBase<AssetServiceClient>
    {
      /// <summary>Creates a new client for AssetService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AssetServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AssetService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AssetServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AssetServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AssetServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::CreateAssetClassResponse CreateAssetClass(global::CreateAssetClassRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateAssetClass(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::CreateAssetClassResponse CreateAssetClass(global::CreateAssetClassRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateAssetClass, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::CreateAssetClassResponse> CreateAssetClassAsync(global::CreateAssetClassRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateAssetClassAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::CreateAssetClassResponse> CreateAssetClassAsync(global::CreateAssetClassRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateAssetClass, null, options, request);
      }
      public virtual global::DeleteAssetClassResponse DeleteAssetClass(global::DeleteAssetClassRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteAssetClass(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DeleteAssetClassResponse DeleteAssetClass(global::DeleteAssetClassRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteAssetClass, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DeleteAssetClassResponse> DeleteAssetClassAsync(global::DeleteAssetClassRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteAssetClassAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DeleteAssetClassResponse> DeleteAssetClassAsync(global::DeleteAssetClassRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteAssetClass, null, options, request);
      }
      public virtual global::CreateAssetResponse CreateAsset(global::CreateAssetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateAsset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::CreateAssetResponse CreateAsset(global::CreateAssetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateAsset, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::CreateAssetResponse> CreateAssetAsync(global::CreateAssetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateAssetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::CreateAssetResponse> CreateAssetAsync(global::CreateAssetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateAsset, null, options, request);
      }
      public virtual global::DeleteAssetResponse DeleteAsset(global::DeleteAssetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteAsset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DeleteAssetResponse DeleteAsset(global::DeleteAssetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteAsset, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::DeleteAssetResponse> DeleteAssetAsync(global::DeleteAssetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteAssetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::DeleteAssetResponse> DeleteAssetAsync(global::DeleteAssetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteAsset, null, options, request);
      }
      public virtual global::TransferAssetResponse TransferAsset(global::TransferAssetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TransferAsset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TransferAssetResponse TransferAsset(global::TransferAssetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TransferAsset, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TransferAssetResponse> TransferAssetAsync(global::TransferAssetRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TransferAssetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TransferAssetResponse> TransferAssetAsync(global::TransferAssetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TransferAsset, null, options, request);
      }
      public virtual global::ExecuteTransactionResponse ExecuteTransaction(global::ExecuteTransactionRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ExecuteTransaction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ExecuteTransactionResponse ExecuteTransaction(global::ExecuteTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExecuteTransaction, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ExecuteTransactionResponse> ExecuteTransactionAsync(global::ExecuteTransactionRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ExecuteTransactionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ExecuteTransactionResponse> ExecuteTransactionAsync(global::ExecuteTransactionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExecuteTransaction, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AssetServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AssetServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(AssetServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateAssetClass, serviceImpl.CreateAssetClass)
          .AddMethod(__Method_DeleteAssetClass, serviceImpl.DeleteAssetClass)
          .AddMethod(__Method_CreateAsset, serviceImpl.CreateAsset)
          .AddMethod(__Method_DeleteAsset, serviceImpl.DeleteAsset)
          .AddMethod(__Method_TransferAsset, serviceImpl.TransferAsset)
          .AddMethod(__Method_ExecuteTransaction, serviceImpl.ExecuteTransaction).Build();
    }

  }
}
#endregion
