// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChatService.proto
// </auto-generated>
// Original file comments:
//
//
//
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Axiverse.Services.Proto {
  public static partial class ChatService
  {
    static readonly string __ServiceName = "ChatService";

    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.CreateChannelRequest> __Marshaller_CreateChannelRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.CreateChannelRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.CreateChannelResponse> __Marshaller_CreateChannelResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.CreateChannelResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.JoinChannelRequest> __Marshaller_JoinChannelRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.JoinChannelRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.JoinChannelResponse> __Marshaller_JoinChannelResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.JoinChannelResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.ChatEvent> __Marshaller_ChatEvent = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.ChatEvent.Parser.ParseFrom);

    static readonly grpc::Method<global::Axiverse.Services.Proto.CreateChannelRequest, global::Axiverse.Services.Proto.CreateChannelResponse> __Method_CreateChannel = new grpc::Method<global::Axiverse.Services.Proto.CreateChannelRequest, global::Axiverse.Services.Proto.CreateChannelResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateChannel",
        __Marshaller_CreateChannelRequest,
        __Marshaller_CreateChannelResponse);

    static readonly grpc::Method<global::Axiverse.Services.Proto.JoinChannelRequest, global::Axiverse.Services.Proto.JoinChannelResponse> __Method_JoinChannel = new grpc::Method<global::Axiverse.Services.Proto.JoinChannelRequest, global::Axiverse.Services.Proto.JoinChannelResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "JoinChannel",
        __Marshaller_JoinChannelRequest,
        __Marshaller_JoinChannelResponse);

    static readonly grpc::Method<global::Axiverse.Services.Proto.ChatEvent, global::Axiverse.Services.Proto.ChatEvent> __Method_Listen = new grpc::Method<global::Axiverse.Services.Proto.ChatEvent, global::Axiverse.Services.Proto.ChatEvent>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Listen",
        __Marshaller_ChatEvent,
        __Marshaller_ChatEvent);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Axiverse.Services.Proto.ChatServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ChatService</summary>
    public abstract partial class ChatServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Axiverse.Services.Proto.CreateChannelResponse> CreateChannel(global::Axiverse.Services.Proto.CreateChannelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Axiverse.Services.Proto.JoinChannelResponse> JoinChannel(global::Axiverse.Services.Proto.JoinChannelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Listen(grpc::IAsyncStreamReader<global::Axiverse.Services.Proto.ChatEvent> requestStream, grpc::IServerStreamWriter<global::Axiverse.Services.Proto.ChatEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ChatService</summary>
    public partial class ChatServiceClient : grpc::ClientBase<ChatServiceClient>
    {
      /// <summary>Creates a new client for ChatService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ChatServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ChatService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ChatServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ChatServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ChatServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Axiverse.Services.Proto.CreateChannelResponse CreateChannel(global::Axiverse.Services.Proto.CreateChannelRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateChannel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Axiverse.Services.Proto.CreateChannelResponse CreateChannel(global::Axiverse.Services.Proto.CreateChannelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateChannel, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.CreateChannelResponse> CreateChannelAsync(global::Axiverse.Services.Proto.CreateChannelRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateChannelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.CreateChannelResponse> CreateChannelAsync(global::Axiverse.Services.Proto.CreateChannelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateChannel, null, options, request);
      }
      public virtual global::Axiverse.Services.Proto.JoinChannelResponse JoinChannel(global::Axiverse.Services.Proto.JoinChannelRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return JoinChannel(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Axiverse.Services.Proto.JoinChannelResponse JoinChannel(global::Axiverse.Services.Proto.JoinChannelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_JoinChannel, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.JoinChannelResponse> JoinChannelAsync(global::Axiverse.Services.Proto.JoinChannelRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return JoinChannelAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.JoinChannelResponse> JoinChannelAsync(global::Axiverse.Services.Proto.JoinChannelRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_JoinChannel, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Axiverse.Services.Proto.ChatEvent, global::Axiverse.Services.Proto.ChatEvent> Listen(grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Listen(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Axiverse.Services.Proto.ChatEvent, global::Axiverse.Services.Proto.ChatEvent> Listen(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Listen, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ChatServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ChatServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ChatServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateChannel, serviceImpl.CreateChannel)
          .AddMethod(__Method_JoinChannel, serviceImpl.JoinChannel)
          .AddMethod(__Method_Listen, serviceImpl.Listen).Build();
    }

  }
}
#endregion
