// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MarketService.proto
// </auto-generated>
// Original file comments:
//
//
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Axiverse.Services.Proto {
  public static partial class MarketService
  {
    static readonly string __ServiceName = "MarketService";

    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.PlaceOrderRequest> __Marshaller_PlaceOrderRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.PlaceOrderRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.PlaceOrderResponse> __Marshaller_PlaceOrderResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.PlaceOrderResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Axiverse.Services.Proto.PlaceOrderRequest, global::Axiverse.Services.Proto.PlaceOrderResponse> __Method_PlaceOrder = new grpc::Method<global::Axiverse.Services.Proto.PlaceOrderRequest, global::Axiverse.Services.Proto.PlaceOrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PlaceOrder",
        __Marshaller_PlaceOrderRequest,
        __Marshaller_PlaceOrderResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Axiverse.Services.Proto.MarketServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MarketService</summary>
    public abstract partial class MarketServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Axiverse.Services.Proto.PlaceOrderResponse> PlaceOrder(global::Axiverse.Services.Proto.PlaceOrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MarketService</summary>
    public partial class MarketServiceClient : grpc::ClientBase<MarketServiceClient>
    {
      /// <summary>Creates a new client for MarketService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MarketServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MarketService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MarketServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MarketServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MarketServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Axiverse.Services.Proto.PlaceOrderResponse PlaceOrder(global::Axiverse.Services.Proto.PlaceOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PlaceOrder(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Axiverse.Services.Proto.PlaceOrderResponse PlaceOrder(global::Axiverse.Services.Proto.PlaceOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PlaceOrder, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.PlaceOrderResponse> PlaceOrderAsync(global::Axiverse.Services.Proto.PlaceOrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PlaceOrderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.PlaceOrderResponse> PlaceOrderAsync(global::Axiverse.Services.Proto.PlaceOrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PlaceOrder, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MarketServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MarketServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MarketServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PlaceOrder, serviceImpl.PlaceOrder).Build();
    }

  }
}
#endregion
