// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Infrastructure/MetricService.proto
// </auto-generated>
// Original file comments:
// Metric Service
//
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Axiverse.Services.Proto {
  public static partial class MetricService
  {
    static readonly string __ServiceName = "MetricService";

    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.RecordCounterRequest> __Marshaller_RecordCounterRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.RecordCounterRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Axiverse.Services.Proto.RecordCounterResponse> __Marshaller_RecordCounterResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Axiverse.Services.Proto.RecordCounterResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Axiverse.Services.Proto.RecordCounterRequest, global::Axiverse.Services.Proto.RecordCounterResponse> __Method_RecordCounter = new grpc::Method<global::Axiverse.Services.Proto.RecordCounterRequest, global::Axiverse.Services.Proto.RecordCounterResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RecordCounter",
        __Marshaller_RecordCounterRequest,
        __Marshaller_RecordCounterResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Axiverse.Services.Proto.MetricServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MetricService</summary>
    public abstract partial class MetricServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Axiverse.Services.Proto.RecordCounterResponse> RecordCounter(global::Axiverse.Services.Proto.RecordCounterRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MetricService</summary>
    public partial class MetricServiceClient : grpc::ClientBase<MetricServiceClient>
    {
      /// <summary>Creates a new client for MetricService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MetricServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MetricService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MetricServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MetricServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MetricServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Axiverse.Services.Proto.RecordCounterResponse RecordCounter(global::Axiverse.Services.Proto.RecordCounterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecordCounter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Axiverse.Services.Proto.RecordCounterResponse RecordCounter(global::Axiverse.Services.Proto.RecordCounterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RecordCounter, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.RecordCounterResponse> RecordCounterAsync(global::Axiverse.Services.Proto.RecordCounterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecordCounterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Axiverse.Services.Proto.RecordCounterResponse> RecordCounterAsync(global::Axiverse.Services.Proto.RecordCounterRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RecordCounter, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MetricServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MetricServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MetricServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RecordCounter, serviceImpl.RecordCounter).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MetricServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RecordCounter, serviceImpl.RecordCounter);
    }

  }
}
#endregion
