version: '3'
services:
  # Identity Service
  identity:
    build:
      context: ../Source
      dockerfile: ../Production/identity-service.dockerfile
    #restart: always
  # Web Server
  web:
    build:
      context: ../Web
      dockerfile: ../Production/web.dockerfile
    ports:
      - "8080:8080"
    restart: always
  # Database
  mysql:
    restart: always
    image: mysql:latest
    env_file:
     - ./mysql-dev.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: