version: '3'
services:
  mysql:
    restart: always
    image: mysql:latest
    env_file:
     - ./mysql-dev.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: