version: '3'
services:
  # Build
  build:
    build:
      context: ../Source
      dockerfile: ../Production/build.dockerfile
  # Entity Service
  entity:
    build:
      context: ../Source
      dockerfile: ../Production/entity-service.dockerfile
    env_file:
      - axiverse.env
    ports:
      - "32001:32001"
    restart: always
  # Identity Service
  identity:
    build:
      context: ../Source
      dockerfile: ../Production/identity-service.dockerfile
    env_file:
      - axiverse.env
    ports:
      - "32000:32000"
    restart: always
  # Web Server
  web:
    build:
      context: ../Web
      dockerfile: ../Production/web.dockerfile
    env_file:
      - axiverse.env
    ports:
      - "8000:8000"
    restart: always
  # Database
  mysql:
    restart: always
    image: mysql:latest
    env_file:
     - ./mysql-dev.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: