apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o .\Kubernetes\
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: chat
  name: chat
spec:
  ports:
  - name: "32002"
    port: 32002
    targetPort: 32002
  selector:
    io.kompose.service: chat
status:
  loadBalancer: {}
