apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o .\Kubernetes\
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: entity
  name: entity
spec:
  ports:
  - name: "32001"
    port: 32001
    targetPort: 32001
  selector:
    io.kompose.service: entity
status:
  loadBalancer: {}
