apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -o .\Kubernetes\
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: identity
  name: identity
spec:
  ports:
  - name: "32000"
    port: 32000
    targetPort: 32000
  selector:
    io.kompose.service: identity
status:
  loadBalancer: {}
